h_t_handcraft/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from h_t_handcraft.views import AboutUsView, TermsAndConditionsView
from products.views import IndexView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('shopping/', include('shopping_cart.urls')),
    path('about/', AboutUsView.as_view(), name='about'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms_and_conditions'),
    path('reset_password/', auth_views.PasswordResetView.as_view
    (template_name="reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view
    (template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view
    (template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name="password_reset_done.html"), name='password_reset_complete'),
    path('products/', include('products.urls', namespace='products')),
]
urlpatterns += i18n_patterns(
    path('set-language/', set_language, name='set_language'),
    prefix_default_language=True
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CategoryProductsView, ProductDetailView, AddToCart, ProductSearchView, CustomProductRequestView, \
    ThankYouView

app_name = "products"

urlpatterns = ([
    path("category/<int:id>/", CategoryProductsView.as_view(), name="category_products"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("add_to_cart/<int:pk>/", AddToCart.as_view(), name="add_to_cart"),
    path("search/", ProductSearchView.as_view(), name="search"),
    path('custom-product-request/', CustomProductRequestView.as_view(), name='custom_product_request'),
    path('thank-you/', ThankYouView.as_view(), name='thank_you')
])

users/urls.py
from django.urls import path
from shopping_cart.views import UserOrders, OrderView
from .views import RegisterView, LoginView, LogoutView, ChangePasswordView, UserProfileView, UserProfileUpdateView, \
    FeedbackView, FeedbackListView, InvoiceView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path("orders/", UserOrders.as_view(), name="user_orders"),
    path("order/<int:id>/", OrderView.as_view(), name="order"),
    path('profile/update/', UserProfileUpdateView.as_view(), name='update_profile'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('feedback/list/', FeedbackListView.as_view(), name='feedback_list'),
    path('invoice/<int:order_id>/', InvoiceView.as_view(), name='invoice'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models

from shopping_cart.models import Cart


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, blank=False)
    last_name = models.CharField(max_length=50, blank=False)
    address = models.CharField(max_length=50, blank=False)
    city = models.CharField(max_length=50, blank=False)
    zipcode = models.CharField(max_length=10, blank=False)
    county = models.CharField(max_length=25, blank=False)
    country = models.CharField(max_length=50, blank=False)
    phone_number = models.CharField(max_length=15, null=False, blank=False)

    class Meta:
        abstract = True


class Order(Address, models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    confirmation = models.BooleanField(default=False)
    cart = models.ForeignKey(Cart, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return (
            f'Order id: {self.id}, '
            f'order date: {self.date_ordered.strftime("%Y-%m-%d")}, '
            f'cart: {self.cart.id}, '
            f'{self.user.first_name} {self.user.last_name}'
        )


class ShippingAddress(Address, models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return f'Tellija: {self.user.first_name} {self.user.last_name}, {self.order.date_ordered}'


class Itella(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    box_name = models.CharField(max_length=50, blank=False)
    phone_number = models.CharField(max_length=15, null=False, blank=False)

    def __str__(self):
        return f'Tellia: {self.user.first_name} {self.user.last_name}, {self.box_name}, {self.phone_number}'


class Omniva(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    box_name = models.CharField(max_length=50, blank=False)
    phone_number = models.CharField(max_length=15, null=False, blank=False)

    def __str__(self):
        return f'Tellia: {self.user.first_name} {self.user.last_name}, {self.box_name}, {self.phone_number}'


class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Feedback from {self.name}"

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)
    phone_number = forms.CharField(max_length=15, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email


class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, required=True)
    password = forms.CharField(max_length=30, required=True, widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data['username']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError("This username does not exist.")
        return username


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    def clean_old_password(self):
        old_password = self.cleaned_data['old_password']
        if old_password != self.cleaned_data['new_password']:
            raise forms.ValidationError("")


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

users/views.py
import os
from datetime import timedelta
from decimal import Decimal
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import EmailMultiAlternatives
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.templatetags.static import static
from django.views import View
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.views.generic import DetailView, UpdateView
from django.contrib import messages
from reportlab.lib.units import cm
from h_t_handcraft import settings
from shopping_cart.models import CartProduct
from .forms import RegistrationForm, UserUpdateForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from .models import User, Order, Feedback
from django.conf import settings
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageTemplate
from reportlab.lib.styles import getSampleStyleSheet


class RegisterView(View):
    def get(self, request):
        form = RegistrationForm()
        return render(request, 'register.html', {'form': form})

    def post(self, request):
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.email = form.cleaned_data.get('email')
            user.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            if user:
                login(request, user)
                return redirect('users:profile')
        return render(request, 'register.html', {'form': form})


class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, 'login.html', {'form': form})

    def post(self, request):
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            print(f"User logged in: {user.username}")

            return redirect('users:profile')
        else:
            print(form.errors)
        return render(request, 'login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('users:login')


class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('users:profile')
    template_name = 'change_password.html'


class UserProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'profile.html'
    context_object_name = 'user_profile'

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(user=self.request.user, cart__is_active=False).order_by('-id')[:5]
        return context


class UserProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'update_profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class FeedbackView(View):
    def get(self, request):
        return render(request, 'feedback.html')

    def post(self, request):
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')

        Feedback.objects.create(name=name, email=email, message=message)

        messages.success(request, 'Thank you for your feedback!')
        return redirect('users:feedback_list')


class FeedbackListView(View):
    def get(self, request):
        feedbacks = Feedback.objects.all().order_by('-created_at')
        return render(request, 'feedback_list.html', {'feedbacks': feedbacks})


class InvoiceView(View):
    def get(self, request, order_id):
        try:
            order = Order.objects.get(id=order_id)
        except Order.DoesNotExist:
            return HttpResponse("Tellimust ei leitud", status=404)

        pdf_file_path = self.generate_pdf(order)
        if pdf_file_path:
            self.send_order_confirmation(order, pdf_file_path)

            with open(pdf_file_path, 'rb') as pdf_file:
                response = HttpResponse(pdf_file.read(), content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="Arve_{order.id}.pdf"'
                return response
        else:
            return HttpResponse("Arve genereerimine ebaõnnestus", status=500)

    def generate_pdf(self, order):
        try:
            # Määrame faili asukoha
            filename = f'Arve_{order.id}.pdf'
            filepath = os.path.join(settings.INVOICE_PATH, filename)

            # Loo PDF
            doc = SimpleDocTemplate(filepath, pagesize=A4)
            styles = getSampleStyleSheet()
            elements = []

            # Jaluse funktsioon
            def add_footer(canvas, doc):
                canvas.saveState()
                canvas.setFont("Helvetica", 9)

                # Jalus
                footer_data = [
                    [
                        "Tartumaa, Kastre vald\nKurepalu\nFIE Ragne Hanko",
                        "Telefon: +372 53304239\nE-post: kunst.on.moes@online.ee\nFacebook: H&T Käsitöö",
                        "Arvelduskonto nr\nEE204204278626434500\nRAGNE HANKO"
                    ]
                ]

                footer_table = Table(
                    footer_data,
                    colWidths=[5 * cm, 7 * cm, 5 * cm]
                )
                footer_table.setStyle(TableStyle([
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ]))

                width, height = A4
                footer_table.wrapOn(canvas, width, height)
                footer_table.drawOn(canvas, 2 * cm, 1 * cm)

                canvas.restoreState()

            # Logo
            logo_path = './templates/static/img/logo_no_2.png'
            try:
                logo = Image(logo_path, width=3.5 * cm, height=3 * cm, hAlign='LEFT')
            except Exception as e:
                raise ValueError(f"Logo laadimise viga: {e}")

            # Pealkiri
            invoice_title = Paragraph(f"<b>ARVE NR {order.id}</b>", styles["Title"])

            # Logo ja pealkirja paigutus
            header_row = Table(
                [
                    [logo, invoice_title]
                ],
                colWidths=[4 * cm, 12 * cm]
            )
            header_row.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ALIGN', (1, 0), (1, 0), 'CENTER'),
                ('TOPPADDING', (1, 0), (1, 0), 1 * cm),
            ]))
            elements.append(header_row)
            elements.append(Spacer(1, 1.5 * cm))

            # Maksetähtaeg
            payment_due_date = order.date_ordered + timedelta(days=3)

            # Saaja
            recipient_info = f"""
            <b>Tellija:</b> {order.first_name} {order.last_name}<br/>
            <b>Tellija kontakt:</b> {order.phone_number}<br/>
            <b>Kuupäev:</b> {order.date_ordered.strftime("%d.%m.%Y")}<br/>
            <b>Maksetähtaeg:</b> {payment_due_date.strftime("%d.%m.%Y")}<br/>
            """

            # Saatja
            sender_info = f"""
            <b>Saatja:</b> FIE Ragne Hanko<br/>
            <b>Registrikood:</b> 14460580<br/>
            """

            # Saaja ja saatja andmete paigutus
            info_table = Table(
                [
                    [Paragraph(recipient_info, styles["Normal"]), Paragraph(sender_info, styles["Normal"])]
                ],
                colWidths=[10 * cm, 6 * cm]
            )
            info_table.setStyle(TableStyle([
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
                ('ALIGN', (0, 0), (0, 0), 'LEFT'),
                ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
            ]))
            elements.append(info_table)
            elements.append(Spacer(1, 2 * cm))

            # Kirjelduste tabeli päis
            data = [[
                Paragraph("Kirjeldus", styles["Normal"]),
                "Kogus",
                "Hind",
                "Summa"
            ]]
            total_sum = 0

            # Tabeli sisu
            for cart_product in CartProduct.objects.filter(cart=order.cart):
                summa = cart_product.quantity * Decimal(cart_product.product.price)
                data.append([
                    Paragraph(cart_product.product.description, styles["Normal"]),
                    cart_product.quantity,
                    f"{cart_product.product.price:.2f} EUR",
                    f"{summa:.2f} EUR"
                ])
                total_sum += summa

            # Kokkuvõtte rida
            data.append(["", "", "Kokku", f"{total_sum:.2f} EUR"])

            # Loome ja kujundame tabeli
            table = Table(data, colWidths=[7 * cm, 3 * cm, 3 * cm, 3 * cm])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 10),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
                ('FONTNAME', (-1, -1), (-1, -1), 'Helvetica-Bold'),

users/templates/change_password.html
{% extends "base.html" %}
{% load i18n %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/change_password.css' %}">
{% endblock %}

{% block content %}
    <div class="container my-3">
        <header class="text-center mb-4">
            <h1>{% trans 'Muuda parooli' %}</h1>
        </header>

        <section>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}

                <div class="d-flex justify-content-between">
                    <button type="submit" class="btn custom-btn">{% trans 'Muuda' %}</button>
                    <a href="{% url 'users:profile' %}" class="btn btn-outline-secondary">{% trans 'Katkesta' %}</a>
                </div>
            </form>
        </section>

        {% if form.errors %}
            <div class="error-messages text-danger mt-4">
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}

users/templates/itella_order.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h2 class="mt-3">{% trans 'Tellimus' %} {{ order_id|stringformat:"06d" }}</h2>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>{% trans 'Toode' %}</th>
                        <th>{% trans 'Kogus' %}</th>
                        <th>{% trans 'Hind' %}</th>
                        <th>{% trans 'Kokku' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td><a href="{% url 'products:detail' item.product.id %}">{{ item.product.title }}</a></td>
                            <td>
                                {{ item.quantity }}
                            </td>
                            <td>{{ item.product.price }}</td>
                            <td>{{ item.total_item_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="fw-bold" colspan="3">{% trans 'Kokku' %}</td>
                        <td class="fw-bold">{{ total_price.total_price }}</td>
                    </tr>
                </tbody>
            </table>
            {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}">
                    <button class="btn btn-primary">{% trans 'Logi sisse / Registreeri' %}</button>
                </a>
            {% endif %}
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>{% trans 'Saaja andmed' %}</h2>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>{% trans 'Saatmise viis' %}</th>
                                <td>Itella</td>
                            </tr>
                            <tr>
                                <th>{% trans 'Pakiautomaat' %}</th>
                                <td>{{ itella.box_name }}</td>
                            </tr>
                            <tr>
                                <th>{% trans 'Telefoni number' %}</th>
                                <td>{{ itella.phone_number }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-3">
    <h1>{% trans 'Logi sisse' %}</h1>

    {% if form.non_field_errors %}
    <div class="error-message">
        {{ form.non_field_errors }}
    </div>
    {% endif %}

    <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}

        <div class="form-group mb-3">
            <label for="username">{% trans 'Kasutajanimi:' %}</label>
            <input type="text" id="username" name="username" placeholder="{% trans 'Sisesta enda kasutajanimi' %}" required>
        </div>

        <div class="form-group mb-3">
            <label for="password">{% trans 'Parool:' %}</label>
            <input type="password" id="password" name="password" placeholder="{% trans 'Sisesta enda parool' %}" required>
        </div>

        <div class="wrap mb-3">
            <button type="submit" class="custom-btn">{% trans 'Logi sisse' %}</button>
        </div>
    </form>

    <a href="{% url 'reset_password' %}" class="footer-link"><i>{% trans 'Unustasid parooli?' %}</i></a>
    <p>{% trans 'Kasutaja puudub?' %} <a href="{% url 'users:register' %}" class="footer-link">{% trans 'Registreeri siin' %}</a>.</p>
</div>
{% endblock %}

users/templates/omniva_order.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h2 class="mt-3">{% trans 'Tellimus' %} {{ order_id|stringformat:"06d" }}</h2>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>{% trans 'Toode' %}</th>
                        <th>{% trans 'Kogus' %}</th>
                        <th>{% trans 'Hind' %}</th>
                        <th>{% trans 'Kokku' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td><a href="{% url 'products:detail' item.product.id %}">{{ item.product.title }}</a></td>
                            <td>
                                {{ item.quantity }}
                            </td>
                            <td>{{ item.product.price }}</td>
                            <td>{{ item.total_item_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="fw-bold" colspan="3">{% trans 'Kokku' %}</td>
                        <td class="fw-bold">{{ total_price.total_price }}</td>
                    </tr>
                </tbody>
            </table>
            {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}">
                    <button class="btn btn-primary">{% trans 'Logi sisse / Registreeri' %}</button>
                </a>
            {% endif %}
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>{% trans 'Saaja andmed' %}</h2>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>{% trans 'Saatmise viis' %}</th>
                                <td>Omniva</td>
                            </tr>
                            <tr>
                                <th>{% trans 'Pakiautomaat' %}</th>
                                <td>{{ omniva.box_name }}</td>
                            </tr>
                            <tr>
                                <th>{% trans 'Telefoni number' %}</th>
                                <td>{{ omniva.phone_number }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/order.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h2 class="mt-3">{% trans 'Tellimus' %} {{ order_id|stringformat:"06d" }} {% trans 'ei leitud' %}</h2>
        </div>
    </div>
{% endblock %}

users/templates/order_address.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h2 class="mt-3">{% trans "Tellimus" %} {{ order_id|stringformat:"06d" }}</h2>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>{% trans "Toode" %}</th>
                        <th>{% trans "Kogus" %}</th>
                        <th>{% trans "Hind" %}</th>
                        <th>{% trans "Kokku" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td><a href="{% url 'products:detail' item.product.id %}">{{ item.product.title }}</a></td>
                            <td>{{ item.quantity }}</td>
                            <td>{{ item.product.price }}</td>
                            <td>{{ item.total_item_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="fw-bold" colspan="3">{% trans "Kokku" %}</td>
                        <td class="fw-bold">{{ total_price.total_price }}</td>
                    </tr>
                </tbody>
            </table>
            {% if not user.is_authenticated %}
                <a href="{% url 'users:login' %}">
                    <button class="btn btn-primary">{% trans "Logi sisse / Registreeri" %}</button>
                </a>
            {% endif %}
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    <h2>{% trans "Saaja andmed" %}</h2>
                </div>
                <div class="card-body">
                    <table class="table table-striped">
                        <tbody>
                            <tr>
                                <th>{% trans "Saatmise viis" %}</th>
                                <td>DPD Kuller</td>
                            </tr>
                            <tr>
                                <th>{% trans "Eesnimi" %}:</th>
                                <td>{{ shipping.first_name }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Perekonnanimi" %}:</th>
                                <td>{{ shipping.last_name }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Aadress" %}:</th>
                                <td>{{ shipping.address }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Linn" %}:</th>
                                <td>{{ shipping.city }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Postiinteks" %}:</th>
                                <td>{{ shipping.zipcode }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Maakond" %}:</th>
                                <td>{{ shipping.country }}</td>
                            </tr>
                            <tr>
                                <th>{% trans "Telefoni number" %}:</th>
                                <td>{{ shipping.phone_number }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <header class="text-center mb-4">
        <h1 class="header-title">{{ user_profile.username }} {% trans "profiil" %}</h1>
    </header>

    <div class="row">
        <div class="col-md-6 mb-5">
            <section>
                <h2 class="h5 text-secondary">{% trans "Personaalne informatsioon" %}</h2>
                <div class="card shadow border-light">
                    <div class="card-body">
                        <p><strong>{% trans "Kasutajanimi:" %}</strong> {{ user_profile.username }}</p>
                        <p><strong>{% trans "Eesnimi:" %}</strong> {{ user_profile.first_name }}</p>
                        <p><strong>{% trans "Perekonnanimi:" %}</strong> {{ user_profile.last_name }}</p>
                        <p><strong>{% trans "Email:" %}</strong> {{ user_profile.email }}</p>
                        <p><strong>{% trans "Telefoni number:" %}</strong> {{ user_profile.phone_number }}</p>
                        <p><strong>{% trans "Kasutaja loodud:" %}</strong> {{ user_profile.created_at }}</p>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <section class="text-center">
        <div class="d-flex justify-content-center flex-wrap">
            <a class="btn btn-edit-profile mx-2" href="{% url 'users:update_profile' %}">{% trans "Muuda profiili" %}</a>
            <a class="btn btn-edit-profile mx-2" href="{% url 'users:change_password' %}">{% trans "Muuda parool" %}</a>
        </div>
    </section>
</div>
{% endblock %}