h_t_handcraft/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from h_t_handcraft.views import AboutUsView, TermsAndConditionsView
from products.views import IndexView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('shopping/', include('shopping_cart.urls')),
    path('about/', AboutUsView.as_view(), name='about'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms_and_conditions'),
    path('reset_password/', auth_views.PasswordResetView.as_view
    (template_name="reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view
    (template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view
    (template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name="password_reset_done.html"), name='password_reset_complete'),
    path('products/', include('products.urls', namespace='products')),
]
urlpatterns += i18n_patterns(
    path('set-language/', set_language, name='set_language'),
    prefix_default_language=True
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CategoryProductsView, ProductDetailView, AddToCart, ProductSearchView, CustomProductRequestView, \
    ThankYouView

app_name = "products"

urlpatterns = ([
    path("category/<int:id>/", CategoryProductsView.as_view(), name="category_products"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("add_to_cart/<int:pk>/", AddToCart.as_view(), name="add_to_cart"),
    path("search/", ProductSearchView.as_view(), name="search"),
    path('custom-product-request/', CustomProductRequestView.as_view(), name='custom_product_request'),
    path('thank-you/', ThankYouView.as_view(), name='thank_you')
])

shopping_cart/urls.py
from django.urls import path

from shopping_cart.views import DeleteFromCart, CartView, Checkout, ShippingAddressView, ShippingItella, \
    ShippingIOmniva, ShippingDPD

app_name = "shopping_cart"

urlpatterns = [
    path("delete/<int:pk>", DeleteFromCart.as_view(), name="delete_from_cart"),

    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", Checkout.as_view(), name="checkout"),
    path("shipping/", ShippingAddressView.as_view(), name="shipping"),
    path("shipping_dpd/", ShippingDPD.as_view(), name="dpd"),
    path("shipping-itella/", ShippingItella.as_view(), name="itella"),
    path("shipping-omniva/", ShippingIOmniva.as_view(), name="omniva"),
]

users/urls.py
from django.urls import path
from shopping_cart.views import UserOrders, OrderView
from .views import RegisterView, LoginView, LogoutView, ChangePasswordView, UserProfileView, UserProfileUpdateView, \
    FeedbackView, FeedbackListView, InvoiceView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path("orders/", UserOrders.as_view(), name="user_orders"),
    path("order/<int:id>/", OrderView.as_view(), name="order"),
    path('profile/update/', UserProfileUpdateView.as_view(), name='update_profile'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('feedback/list/', FeedbackListView.as_view(), name='feedback_list'),
    path('invoice/<int:order_id>/', InvoiceView.as_view(), name='invoice'),
]

shopping_cart/models.py
from django.contrib.auth.models import User
from django.db import models
from products.models import Product
from products.models import Product


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f'Cart id: {self.id}, user: {self.user}, date added: {self.date_added.strftime("%Y-%m-%d %H:%M:%S")}'


class CartProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(null=True)

    def total_item_price(self):
        return self.quantity * self.product.price

    def __str__(self):
        user = self.cart.user
        return (f'[Tellija: {user.first_name} {user.last_name}], {self.product.title}, Hind: €{self.product.price}, '
                f'Kogus: {self.quantity} tk.')

shopping_cart/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, F
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from users.models import Order, ShippingAddress, Address, Itella, Omniva
from users.views import InvoiceView
from .models import Cart, CartProduct
from .utils import send_invoice_email


class UserOrders(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        orders = Order.objects.filter(user_id=self.request.user, cart__is_active=False).order_by("id")
        return render(request, 'user_orders.html', {'orders': orders})


class OrderView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        order_id = self.kwargs.get('id')
        cart_items = CartProduct.objects.filter(cart_id__order=order_id, cart__is_active=False).order_by('-id')
        total_price = cart_items.aggregate(total_price=Sum(F('quantity') * F('product__price')))['total_price']

        context = {
            'cart_items': cart_items,
            'total_price': total_price,
            'order_id': order_id
        }

        template = 'order.html'  # fallback template

        try:
            shipping = ShippingAddress.objects.get(order_id=order_id)
            template = 'order_address.html'
            context.update({
                'shipping': shipping
            })
            return render(request, template, context)
        except ShippingAddress.DoesNotExist:
            pass

        try:
            itella = Itella.objects.get(order_id=order_id)
            template = 'itella_order.html'
            context.update({
                'itella': itella
            })
            return render(request, template, context)
        except Itella.DoesNotExist:
            pass

        try:
            omniva = Omniva.objects.get(order_id=order_id)
            template = 'omniva_order.html'
            context.update({
                'omniva': omniva
            })
            return render(request, template, context)
        except Omniva.DoesNotExist:
            pass

        return render(request, template, context)


class CartView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        cart_id = Cart.objects.filter(is_active=True, user=self.request.user).first()
        cart_items = CartProduct.objects.filter(cart=cart_id, cart__is_active=True).order_by('-id')
        total_price = cart_items.aggregate(total_price=Sum(F('quantity') * F('product__price')))

        if not cart_items:
            return render(request, 'cart.html')
        return render(request, 'cart.html', {
                                                    'cart_items': cart_items,
                                                    'total_price': total_price
                                                })


class DeleteFromCart(View):
    def post(self, request, pk):
        cart_product = CartProduct.objects.get(id=pk)
        if cart_product.quantity > 1:
            cart_product.quantity -= 1
            cart_product.save()
        else:
            cart_product.delete()
        return redirect(request.META['HTTP_REFERER'])


class Checkout(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        try:
            contact = Order.objects.get(user=self.request.user, cart__is_active=True)
        except Order.DoesNotExist or None:
            contact = None
        return render(request, 'checkout.html', {'contact': contact})

    def post(self, request):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        address = request.POST.get('address')
        city = request.POST.get('city')
        county = request.POST.get('county')
        zipcode = request.POST.get('zipcode')
        country = request.POST.get('country')
        phone_number = request.POST.get('phone_number')

        try:
            order = Order.objects.get(user_id=self.request.user, cart__is_active=True)
        except Order.DoesNotExist or None:
            order = Order()
        order.cart = Cart.objects.get(user_id=self.request.user, is_active=True)
        order.user = self.request.user
        order.first_name = first_name
        order.last_name = last_name
        order.email = email
        order.address = address
        order.city = city
        order.county = county
        order.zipcode = zipcode
        order.country = country
        order.phone_number = phone_number
        order.save()

        return redirect(reverse('shopping_cart:shipping'))


class ShippingAddressView(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        cart_total = CartProduct.objects.filter(cart__is_active=True,
                                                cart__user=self.request.user
                                                ).aggregate(cart_total=Sum(F('quantity') * F('product__price')))

        return render(request, 'shipping.html', cart_total)


class ShippingDPD(LoginRequiredMixin, View):
    def get(self, request, **kwargs):
        return render(request, 'shipping_options/dpd_kuller.html')

    def post(self, request):
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        address = request.POST.get('address')
        city = request.POST.get('city')
        county = request.POST.get('county')
        zipcode = request.POST.get('zipcode')
        country = request.POST.get('country')
        phone_number = request.POST.get('phone_number')

        shipping = ShippingAddress()
        shipping.order_id = Order.objects.get(user_id=self.request.user, cart__is_active=True).id
        shipping.user = self.request.user
        shipping.first_name = first_name
        shipping.last_name = last_name
        shipping.address = address
        shipping.city = city
        shipping.county = county
        shipping.zipcode = zipcode
        shipping.country = country
        shipping.phone_number = phone_number
        shipping.save()

        cart = Cart.objects.get(user_id=self.request.user, is_active=True)
        send_invoice_email(self.request.user)
        cart.is_active = False
        cart.save()

        return redirect(reverse('users:user_orders'))


class ShippingItella(LoginRequiredMixin, View):
    def get (self, request, **kwargs):
        return render(request, 'shipping_options/itella.html')

    def post(self, request):
        itella = Itella()
        itella.user = self.request.user
        itella.order = Order.objects.get(user_id=self.request.user, cart__is_active=True)
        itella.box_name = request.POST.get('sp_name2')
        itella.phone_number = request.POST.get('phone_number')
        itella.save()

        cart = Cart.objects.get(user_id=self.request.user, is_active=True)
        send_invoice_email(self.request.user)
        cart.is_active = False
        cart.save()

        return redirect(reverse('users:user_orders'))


class ShippingIOmniva(LoginRequiredMixin, View):
    def get (self, request, **kwargs):
        return render(request, 'shipping_options/omniva.html')

    def post(self, request):
        omniva = Omniva()
        omniva.user = self.request.user
        omniva.order = Order.objects.get(user_id=self.request.user, cart__is_active=True)
        omniva.box_name = request.POST.get('omniva_selection_value2')
        omniva.phone_number = request.POST.get('phone_number')
        omniva.save()

        cart = Cart.objects.get(user_id=self.request.user, is_active=True)
        send_invoice_email(self.request.user)
        cart.is_active = False
        cart.save()

        return redirect(reverse('users:user_orders'))

shopping_cart/templates/cart.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'cart.css' %}">
{% endblock %}

{% block content %}
    <div class="cart-container">
        {% if cart_items %}
            <table class="table table-striped table-hover cart-table">
                <thead>
                    <tr>
                        <th>{% trans "Toode" %}</th>
                        <th>{% trans "Kogus" %}</th>
                        <th>{% trans "Hind €" %}</th>
                        <th>{% trans "Kokku €" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>{{ item.product.title }}</td>
                            <td>
                                <form action="{% url 'shopping_cart:delete_from_cart' item.id %}" method="post" class="d-inline mx-2">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-danger btn-sm" type="submit">-</button>
                                </form>
                                {{ item.quantity }}
                                <form action="{% url 'products:add_to_cart' item.product.id %}" method="post" class="d-inline mx-2">
                                    {% csrf_token %}
                                    <button class="btn btn-outline-success btn-sm" type="submit">+</button>
                                </form>
                            </td>
                            <td>{{ item.product.price }}</td>
                            <td>{{ item.total_item_price }}</td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" class="fw-bold">{% trans "Kokku" %}</td>
                        <td class="fw-bold">{{ total_price.total_price }}</td>
                    </tr>
                </tbody>
            </table>
            <div class="mt-3">
                <a href="{% url 'shopping_cart:checkout' %}">
                    <button class="btn btn-checkout">{% trans "Kinnita tellimus" %}</button>
                </a>
            </div>
        {% else %}
            <h4 class="text-muted">{% trans "Tooteid ei ole listud ostukorvi" %}</h4>
        {% endif %}

        {% if not user.is_authenticated %}
            <a href="{% url 'users:login' %}">
                <button class="btn btn-primary">{% trans "Logi sisse / Registreeri" %}</button>
            </a>
        {% endif %}
    </div>
{% endblock %}

shopping_cart/templates/checkout.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block style %}
    <link rel="stylesheet" href="{% static 'checkout.css' %}">
    <link rel="stylesheet" type="text/css" href="https://itella.ee/widget/smartpost-terminals.css"/>
{% endblock %}

{% block content %}

<div class="checkout-container">
    <h1 class="checkout-title text-center">{% trans "Kinnita tellimus" %}</h1>
    <div class="checkout-summary">
        <h5 class="checkout-summary-title">{% trans "Tellija informatsioon" %}</h5>
        <form method="post">
            {% csrf_token %}
            <div class="checkout-form">
                <div class="form-group">
                    <label for="first_name">{% trans "Eesnimi" %}</label>
                    <input type="text" id="first_name" name="first_name" value="{{ user.first_name }}" required/>
                </div>

                <div class="form-group">
                    <label for="last_name">{% trans "Perekonnanimi" %}</label>
                    <input type="text" id="last_name" name="last_name" value="{{ user.last_name }}" required/>
                </div>

                <div class="form-group">
                    <label for="email">{% trans "E-Mail" %}</label>
                    <input type="email" id="email" name="email" value="{{ user.email }}" required/>
                </div>

                <h6 class="checkout-summary-title">{% trans "Aadress" %}</h6>
                <div class="form-group">
                    <label for="address">{% trans "Aadress" %}</label>
                    <input type="text" id="address" name="address" value="{{ contact.address }}" required/>
                </div>

                <div class="form-group">
                    <label for="city">{% trans "Linn" %}</label>
                    <input type="text" id="city" name="city" value="{{ contact.city }}" required/>
                </div>

                <div class="form-group">
                    <label for="county">{% trans "Maakond" %}</label>
                    <input type="text" id="county" name="county" value="{{ contact.county }}" required/>
                </div>

                <div class="form-group">
                    <label for="zipcode">{% trans "Postiinteks" %}</label>
                    <input type="text" id="zipcode" name="zipcode" value="{{ contact.zipcode }}" required/>
                </div>

                <div class="form-group">
                    <label for="country">{% trans "Riik" %}</label>
                    <input type="text" id="country" name="country" value="{{ contact.country }}" required/>
                </div>

                <div class="form-group">
                    <label for="phone_number">{% trans "Telefoni number" %}</label>
                    <input type="tel" id="phone_number" name="phone_number" value="{{ contact.phone_number }}" required/>
                </div>

                <button type="submit" class="checkout-confirm-btn">{% trans "Kinnita tellija andmed" %}</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

shopping_cart/templates/shipping.html
{% extends "base.html" %}

{% load static %}
{% load i18n %}

{% block style %}
    <link rel="stylesheet" href="{% static 'checkout.css' %}">
{% endblock %}

{% block content %}

<div class="checkout-container">
    <h1 class="checkout-title text-center">{% trans "Saatmine" %}</h1>
    <div class="checkout-summary">
      <div class="row">
        <div class="col">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="shipping" id="shipping-itella" value="itella" checked>
            <label class="form-check-label" for="shipping-itella">
              Itella
            </label>
          </div>
        </div>
        <div class="col">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="shipping" id="shipping-omniva" value="omniva">
            <label class="form-check-label" for="shipping-omniva">
              Omniva
            </label>
          </div>
        </div>
        <div class="col">
          <div class="form-check">
            <input class="form-check-input" type="radio" name="shipping" id="shipping-dpd" value="dpd">
            <label class="form-check-label" for="shipping-dpd">
              DPD Kuller
            </label>
          </div>
        </div>
      </div>
      <hr>
      <p>{% trans "Vahesumma" %}: €<span id="total-cart-price">{{ cart_total }}</span></p>
      <p>{% trans "Saatmine" %}: €<span id="shipping-price-container"></span></p>
      <p>{% trans "Kokku" %}: €<span id="total-price-container"></span></p>
      <hr>
      <div id="itella-container" style="display: none">
          {% include "shipping_options/itella.html" %}
      </div>
      <div id="omniva-container" style="display: none;">
          {% include "shipping_options/omniva.html" %}
      </div>
      <div id="dpd-container" style="display: none;">
          {% include "shipping_options/dpd_kuller.html" %}
      </div>
    </div>
</div>

<script src="{% static 'js/shipping_choice.js' %}"></script>

{% endblock %}

shopping_cart/templates/user_orders.html
{% extends 'base.html' %}

{% block content %}
    {% for order in orders %}
        <a href="{% url 'shopping_cart:order' order.id %}">
            <h4>{{ order }}</h4>
        </a>
    {% endfor %}
{% endblock %}