h_t_handcraft/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from h_t_handcraft.views import AboutUsView, TermsAndConditionsView
from products.views import IndexView
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import set_language

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('shopping/', include('shopping_cart.urls')),
    path('about/', AboutUsView.as_view(), name='about'),
    path('terms-and-conditions/', TermsAndConditionsView.as_view(), name='terms_and_conditions'),
    path('reset_password/', auth_views.PasswordResetView.as_view
    (template_name="reset_password.html"), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view
    (template_name="password_reset_sent.html"), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view
    (template_name="password_reset_form.html"), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view
    (template_name="password_reset_done.html"), name='password_reset_complete'),
    path('products/', include('products.urls', namespace='products')),
]
urlpatterns += i18n_patterns(
    path('set-language/', set_language, name='set_language'),
    prefix_default_language=True
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CategoryProductsView, ProductDetailView, AddToCart, ProductSearchView, CustomProductRequestView, \
    ThankYouView

app_name = "products"

urlpatterns = ([
    path("category/<int:id>/", CategoryProductsView.as_view(), name="category_products"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("add_to_cart/<int:pk>/", AddToCart.as_view(), name="add_to_cart"),
    path("search/", ProductSearchView.as_view(), name="search"),
    path('custom-product-request/', CustomProductRequestView.as_view(), name='custom_product_request'),
    path('thank-you/', ThankYouView.as_view(), name='thank_you')
])

shopping_cart/urls.py
from django.urls import path

from shopping_cart.views import DeleteFromCart, CartView, Checkout, ShippingAddressView, ShippingItella, \
    ShippingIOmniva, ShippingDPD

app_name = "shopping_cart"

urlpatterns = [
    path("delete/<int:pk>", DeleteFromCart.as_view(), name="delete_from_cart"),

    path("cart/", CartView.as_view(), name="cart"),
    path("checkout/", Checkout.as_view(), name="checkout"),
    path("shipping/", ShippingAddressView.as_view(), name="shipping"),
    path("shipping_dpd/", ShippingDPD.as_view(), name="dpd"),
    path("shipping-itella/", ShippingItella.as_view(), name="itella"),
    path("shipping-omniva/", ShippingIOmniva.as_view(), name="omniva"),
]

users/urls.py
from django.urls import path
from shopping_cart.views import UserOrders, OrderView
from .views import RegisterView, LoginView, LogoutView, ChangePasswordView, UserProfileView, UserProfileUpdateView, \
    FeedbackView, FeedbackListView, InvoiceView

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path("orders/", UserOrders.as_view(), name="user_orders"),
    path("order/<int:id>/", OrderView.as_view(), name="order"),
    path('profile/update/', UserProfileUpdateView.as_view(), name='update_profile'),
    path('feedback/', FeedbackView.as_view(), name='feedback'),
    path('feedback/list/', FeedbackListView.as_view(), name='feedback_list'),
    path('invoice/<int:order_id>/', InvoiceView.as_view(), name='invoice'),
]

products/models.py
from django.db import models
from django.db.models import F
from django.db.models.signals import post_migrate
from django.dispatch import receiver


class Category(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    price = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False)
    image_path = models.ImageField(upload_to='products/img', null=True, blank=True)
    stock = models.IntegerField(default=0, null=False, blank=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    height = models.FloatField(null=True, blank=True)
    width = models.FloatField(null=True, blank=True)
    length = models.FloatField(null=True, blank=True)
    weight = models.FloatField(null=True, blank=True)

    def __str__(self):
        category_name = Category.objects.get(id=self.category.id)
        return f'{category_name} --- {self.title}, Laos: {self.stock}'

    def update_title_et(self):
        self.title_et = self.title
        self.save()


class GalleryImage(models.Model):
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='gallery/')

    def __str__(self):
        return self.title

templates/about_us.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Meist</h1>
    <div class="row">
        <div class="col">
            <h3>EE:</h3>
            <p>
                Oleme nagu hunt kriimsilmad alati 101 asja käsil.<br>
                Oleme seadnud eesmärgiks ,et kahe nädala jooksul tooted kliendini jõuaksid.<br>
                Kui kulub rohkem aega siis anname teada.<br>
                Oleme alati uuteks väljakutseteks valmis. Piisab kui on idee.<br>
                Samas oleme tulnud kliendi soovile ka vastu ja kiirtellimusi teinud.<br>
                Aga nagu teie siis vajame meie ka uneaega.<br>
                Kui sul on mingeid küsimusi või muresid võta julgelt ühendust:<br>
                Keskmiselt vastame kirjadele 1tööpäeva jooksul. <br>
                E-mail: kunst.on.moes@online.ee<br>
                Tel: +372 53304239<br>
                Facebook: H&T Käsitöö
            </p>
        </div>
        <div class="col">
            <h3>EN:</h3>
            <p>
                Like a wolf with scratchy eyes, we are always up to 101 things.<br>
                We have set the goal that the products will reach the customer within two weeks.<br>
                If it takes more time, we will let you know.<br>
                We are always ready for new challenges. It's enough to have an idea.<br>
                At the same time, we have responded to the customer's request and made express orders.<br>
                But like you, we also need sleep time.<br>
                If you have any questions or problems feel free to contact us:<br>
                On average, we answer letters within 1 working day.<br>
                E-mail: kunst.on.moes@online.ee<br>
                Tel: +372 53304239<br>
                Facebook: H&T Käsitöö
            </p>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}H&T Käsitöö{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block style %}
    {% endblock %}
</head>
<body class="bg-light">
<div class="container-fluid">

    <header class="row bg-light py-3 align-items-center">
        <div class="col-3">
            <div class="logo">
                <a href="{% url 'index' %}">
                    <img class="logo-img" src="{% static 'img/logo_no_2.png' %}" alt="Logo">
                </a>
            </div>
        </div>

        <div class="col-6 text-center">
            <h4 class="custom-font">{% trans "Sinu ideed, meie teostus – sinu mõtted, meie teod!" %}</h4>
            <form action="{% url 'products:search' %}" method="get" aria-label="{% trans 'Otsing' %}">
                <div class="input-group">
                    <input type="text" class="form-control" name="q" placeholder="{% trans 'Otsi tooteid...' %}"
                           aria-label="{% trans 'Product search' %}">
                    <button class="btn btn-outline-secondary" type="submit">{% trans 'Otsi' %}</button>
                </div>
            </form>
        </div>

        <div class="col-3 text-end main-button-group">

            {% if user.is_authenticated %}
                <a href="{% url 'shopping_cart:cart' %}">
                    <button class="btn btn-default">
                        🛒
                        <span class="badge bg-secondary">{{ cart_items_count }}</span>
                    </button>
                </a>
                <a href="{% url 'users:user_orders' %}">
                    <button class="btn btn-default">{% trans "Tellimused" %}</button>
                </a>
                <a href="{% url 'users:profile' %}">
                    <button class="btn btn-default">{% trans "Profiil" %}</button>
                </a>
                <a href="{% url 'users:logout' %}">
                    <button class="btn btn-default-custom">{% trans "Logi välja" %}</button>
                </a>
            {% else %}
                <a href="{% url 'users:login' %}">
                    <button class="btn btn-default">{% trans "Logi sisse / Registreeri" %}</button>
                </a>
            {% endif %}
        </div>
    </header>

    <div class="row">
        <nav class="col-md-3 col-lg-2 bg-light sidebar">
            <ul class="nav flex-column">
                <hr class="p-0 m-0">
                {% for category in categories %}
                  <li class="nav-item active">
                        <a class="nav-link fw-bold " aria-current="page"
                           href="{% url 'products:category_products' category.id %}">{% trans category.name %}</a>
                    </li>
                    <hr class="p-0 m-0">
                {% endfor %}
                <li class="nav-item active">
                    <a class="nav-link fw-bold" aria-current="page" href="{% url 'products:custom_product_request' %}">
                        {% trans "Erilahendused" %}
                    </a>
                </li>
                <hr class="p-0 m-0">
            </ul>

            {% include 'weather.html' %}
            <div class="absolute-bottom d-flex flex-column">
                <a href="{% url 'about' %}" class="me-3">{% trans "Meist" %}</a>
                <a href="{% url 'users:feedback' %}" class="me-3">{% trans "Tagasiside" %}</a>
                <a href="{% url 'users:feedback_list' %}" class="mt-0.5">{% trans "Jäetud tagasiside" %}</a>
            </div>

        </nav>

        <main class="col-md-8 col-lg-10">
            <div class="product-list bg-white p-3 border rounded">
                {% block content %}
                {% endblock %}
            </div>
        </main>
    </div>

    <footer class="row bg-light py-3 text-center position-relative">
        <div class="col">
            | Janek: <a href="https://www.linkedin.com/in/janek-sitsmann-752a392b0/" target="_blank">LinkedIn</a> |
            Triinu: <a href="https://www.linkedin.com/in/triinu-n-9b1309262/" target="_blank">LinkedIn</a> |
            Indrek: <a href="https://www.linkedin.com/in/indrek-kuusk-2aa9a874/" target="_blank">LinkedIn</a> |
        </div>
        <div class="flag-container">
            <form method="post" action="{% url 'set_language' %}" class="flag-form">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" name="language" value="et" class="btn">🇪🇪</button>
                <button type="submit" name="language" value="en" class="btn">🇬🇧</button>
                <button type="submit" name="language" value="ru" class="btn">🇷🇺</button>
                <button type="submit" name="language" value="es" class="btn">🇪🇸</button>
            </form>
        </div>
    </footer>


</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load i18n %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'css/product_list.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        {% for product in random_products %}
            <div class="col-md-6 col-lg-5 col-xl-4 col-xxl-3 h-100">
                <div class="card h-100 bg-light mb-3">
                    <a href="{% url 'products:detail' product.id %}" class="text-decoration-none">
                        {% if product.image_path %}
                            <img src="{{ product.image_path.url }}" class="card-img-top" alt="{{ product.title }}">
                        {% else %}
                            <img src="{% static 'img/default_image.png' %}" class="card-img-top" alt="{% trans 'Vaikimisi pilt' %}">
                        {% endif %}
                        <div class="card-body d-flex flex-column">
                            <h2 class="mb-0 text-muted">{{ product.title }}</h2>
                            <p class="text-secondary small">{% trans 'Laojääk' %}: {{ product.stock }}</p>
                            <p class="text-muted fw-bold">{% trans 'Hind' %}: €{{ product.price }}</p>
                            <a href="{% url 'products:detail' product.id %}" class="btn btn-secondary mt-auto">{% trans 'Vaata lähemalt' %}</a>
                        </div>
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/terms_and_conditions.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Üldtingimused</h1>
    <p>Need on meie veebisaidi ja teenuste kasutamise tingimused.</p>
</div>
{% endblock %}

templates/weather.html
{% load i18n %}
{% load static %}

<section class="mt-4">
    <div class="position-relative">
        <img id="seasonal-image" src="{% static 'spring.jpg' %}" class="rounded fixed-size" alt="season">

        <div class="card-img-overlay mx-3 mt-3">
            <h6 class="mb-1" style="font-size: 0.9rem; font-weight: 600;" id="city">{{ weather_data.city }}</h6>
            <p class="h6 my-1"
               style="font-size: 1.2rem; font-weight: 600;" id="temperature">{{ weather_data.temperature }}°C</p>
            <p class="mb-1" style="font-size: 0.8rem; font-weight: 600;">{% trans 'Tajutav' %}:
                <strong id="feels-like-value">{{ weather_data.feels_like }}°C</strong></p>
            <p class="mb-1"
               style="font-size: 0.8rem; font-weight: 600;" id="description">{{ weather_data.description }}</p>
        </div>
    </div>
    <div id="status" style="margin-top: 10px; color: white;"></div>
</section>

<script>
    async function fetchWeatherData(lat, lon) {
        const apiKey = 'WEATHER_API_KEY';
        const weatherUrl = `http://api.openweathermap.org/data/3.0/weather?lat=${lat}&lon=${lon}&units=metric&appid=${apiKey}&lang={{ LANGUAGE_CODE }}`;

        try {
            const response = await fetch(weatherUrl);
            const data = await response.json();

            if (data.cod === 200) {
                document.getElementById('city').textContent = data.name;
                document.getElementById('temperature').textContent = `${data.main.temp}°C`;
                document.getElementById('feels-like-value').textContent = `${data.main.feels_like}°C`;
                document.getElementById('description').textContent = data.weather[0].description;
                setSeasonalBackground();
            } else {
                console.error('Error fetching weather data:', data.message);
            }
        } catch (error) {
            console.error('Error fetching weather data:', error);
        }
    }

    function geoFindMe() {
        const status = document.querySelector("#status");

        if (!navigator.geolocation) {
            status.textContent = "{% trans 'Geolocation is not supported by your browser' %}";
        } else {
            status.textContent = "{% trans 'Locating…' %}";
            navigator.geolocation.getCurrentPosition(success, error);
        }

        function success(position) {
            const latitude = position.coords.latitude;
            const longitude = position.coords.longitude;

            status.textContent = "{% trans 'Location found.' %}";
            fetchWeatherData(latitude, longitude);
        }

        function error() {
            status.textContent = "{% trans 'Unable to retrieve your location' %}";
        }
    }

    function setSeasonalBackground() {
        const seasonalImage = document.getElementById('seasonal-image');
        const month = new Date().getMonth();

        if (month === 11 || month === 0 || month === 1) {
            seasonalImage.src = '{% static "winter.jpg" %}';
        } else if (month >= 2 && month <= 4) {
            seasonalImage.src = '{% static "spring.jpg" %}';
        } else if (month >= 5 && month <= 7) {
            seasonalImage.src = '{% static "summer.jpg" %}';
        } else {
            seasonalImage.src = '{% static "fall.jpg" %}';
        }

        const overlay = document.querySelector('.card-img-overlay');
        overlay.style.color = (month === 11 || month === 0 || month === 1 || month >= 8) ? '#FFFFFF' : '#000000';
    }

    window.onload = () => {
        setSeasonalBackground();
        geoFindMe();
    };
</script>